import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import '../../../../public/css/leave/AdminLeaveList.css';
const AdminLeaveList = ({ leaves, onApprove, onReject, onDelete, }) => {
    return (_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: "Danh s\u00E1ch \u0111\u01A1n ngh\u1EC9 (Admin)" }), _jsxs("table", { className: "min-w-full bg-white shadow-md rounded-lg overflow-hidden border-collapse", children: [_jsx("thead", { className: "bg-gray-200 text-sm", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2 text-left", children: "ID" }), _jsx("th", { className: "px-4 py-2 text-left", children: "Nh\u00E2n vi\u00EAn" }), _jsx("th", { className: "px-4 py-2 text-left", children: "T\u1EEB ng\u00E0y" }), _jsx("th", { className: "px-4 py-2 text-left", children: "\u0110\u1EBFn ng\u00E0y" }), _jsx("th", { className: "px-4 py-2 text-left", children: "L\u00FD do" }), _jsx("th", { className: "px-4 py-2 text-left", children: "Tr\u1EA1ng th\u00E1i" }), _jsx("th", { className: "px-4 py-2 text-left", children: "H\u00E0nh \u0111\u1ED9ng" })] }) }), _jsx("tbody", { children: leaves.map((leave) => (_jsxs("tr", { className: "border-t hover:bg-gray-100", children: [_jsx("td", { className: "px-4 py-2", children: leave.id }), _jsx("td", { className: "px-4 py-2", children: leave.employee?.full_name }), _jsx("td", { className: "px-4 py-2", children: leave.start_date }), _jsx("td", { className: "px-4 py-2", children: leave.end_date }), _jsx("td", { className: "px-4 py-2", children: leave.reason }), _jsx("td", { className: "px-4 py-2", children: _jsx("span", { className: `px-2 py-1 rounded-full text-sm ${leave.status === 'pending'
                                            ? 'bg-yellow-400 text-black'
                                            : leave.status === 'approved'
                                                ? 'bg-green-400 text-white'
                                                : 'bg-red-400 text-white'}`, children: leave.status }) }), _jsx("td", { className: "px-4 py-2 space-x-2", children: leave.status === 'pending' ? (_jsxs(_Fragment, { children: [_jsx("button", { onClick: () => onApprove(leave.id), className: "bg-green-500 text-white px-3 py-1 rounded-md hover:bg-green-600 transition duration-200", children: "Duy\u1EC7t" }), _jsx("button", { onClick: () => onReject(leave.id), className: "bg-yellow-500 text-white px-3 py-1 rounded-md hover:bg-yellow-600 transition duration-200", children: "T\u1EEB ch\u1ED1i" })] })) : (_jsx("button", { onClick: () => onDelete(leave.id), className: "bg-red-500 text-white px-3 py-1 rounded-md hover:bg-red-600 transition duration-200", children: "X\u00F3a" })) })] }, leave.id))) })] })] }));
};
export default AdminLeaveList;
